definitions:
  Message:
    type: object
    required:
      - fullNames
      - email
      - subject
      - text
    properties:
      fullNames:
        type: string
      email:
        type: string
      subject:
        type: string
      text:
        type: string

paths:
  /api/v1/message:
    post:
      tags:
        - Message
      summary: New Message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/Message'
      responses:
        '201':
          description: Message is successfully sent
        '500':
          description: Internal server error
        '400':
          description: Bad request